import type { Metadata } from "next";
import "@/globals.css";
import { ReactQueryProvider } from "@/hooks/query";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { NextUIProvider } from "@nextui-org/react";
import { AuthProvider } from "@/hooks/useAuth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="light w-full h-full">
      <body className={`antialiased w-full h-full`}>
        <ReactQueryProvider>
          <NextUIProvider className="w-full h-full">
            {children}
            <ToastContainer />
          </NextUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
